### ISSUE TITLE
PCRE syntax

### ISSUE THREAD

**Issue by Manc** [samsouder/reggy#17]
Does Reggy support the PCRE syntax as it's used in PHP? If not, can you add it?

Sorry if this isn't the right place to ask this question. I couldn't find any information about this and it's not in the list in the preferences (Reggy 1.3).

**Comment by samsouder** [comment]
PCRE stands for Perl Compatible Regular Expressions, which means that the Perl syntax in the preferences should be what you need. That is what I use for development of PHP regular expressions.

**Comment by Manc** [comment]
Thanks I'll try it! Was confused because this page http://www.php.net/manual/en/reference.pcre.pattern.differences.php lists some differences...

**Comment by samsouder** [comment]
Yeah, there are some differences, but it works for _most_ tasks. I am using the Oniguruma engine to run the expressions and offer all the syntaxes it offers, so we get what we get at this point.
