### ISSUE TITLE
Mavericks Incompatible?

### ISSUE THREAD

**Issue by whoughton** [samsouder/reggy#20]
Seeing the following console logs when trying to open Reggy, is it DOA on Mavericks?

11/22/13 12:53:02.813 PM com.apple.launchd.peruser.501[190]: (com.SamSouder.Reggy.120064[68829]) Job failed to exec(3) for weird reason: 13
11/22/13 12:53:02.814 PM Finder[230]: 8837325: Attempting to SIGCONT to pid #68829 failed, with errno=#3, or the process failed to actually start
11/22/13 12:53:02.816 PM Dock[228]: no information back from LS about running process LSASN:{hi=0x0;lo=0xa7da7d}
11/22/13 12:53:02.824 PM Finder[230]: 8837325: Attempting to SIGCONT to pid #68829 failed, with errno=#3, or the process failed to actually start

**Comment by samsouder** [comment]
Wow, not sure why that’s happening for you. Reggy continues to truck on for me on my upgraded Mavericks boxes.

**Comment by whoughton** [comment]
Thanks, I'll keep digging and post any useful updates I can find! I do somewhat enjoy that it actually says "Job failed to exec(3) for weird reason"

**Comment by whoughton** [comment]
Sorry, I should have done more digging on that error before posting this. It turns out that the Reggy.app/Contents/MacOS/Reggy file had gone from 755 permissions to 744 and as such that was keeping it from opening. Switching permissions back to 755 and it works happily.
