### ISSUE TITLE
Rebuild v1.3 for modern versions of macOS?

### ISSUE THREAD

**Issue by basictheprogram** [samsouder/reggy#27]
Is there the ability to rebuild this application for a modern version of macOS?

**Comment by samsouder** [comment]
As others have mentioned in issue #25, the underlying framework used for allowing the use of multiple regular expression engines would need updated so a straight up rebuild isn't going to work. I haven't made Reggy a priority for a long time, but anyone is free to work on it and submit PRs to modernize it.

**Comment by basictheprogram** [comment]
Thanks for the quick response. I didn't see #25, but I'll sub to that issue and close this one.
